services:
  frontend:
    build: ./app/frontend
    ports:
      - 80:80
    restart: always
    depends_on:
      - backend
    networks:
      - virtual-front
  backend:
    build: ./app/backend
    expose:
      - 3000
    restart: always
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - virtual-front
      - virtual-db
  database:
    image: mysql:8.4
    expose:
      - 3306 # apenas expõe a porta, já que não vamos utilizar fora do container, apenas dentro, expose facilita para outros conainers
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - virtual-db

volumes:
  mysql_data:

networks:
  virtual-front:
  virtual-db:
